const enum Endpoints {
  root = '/',
  login = '/signin',
  current = '/current',
  user = '/user',
  prices = '/prices',
  periods = '/periods',
  payments = '/payments',
  dynamicId = 'id',
  fullAccess = `/:${dynamicId}/fullAccess`,
  houses = `/:${dynamicId}/houses`,
  subscribers = `/:${dynamicId}/subscribers`,
  accounting = `/:${dynamicId}/accounting`,
  documents = `/:${dynamicId}/documents`,
  counters = `/:${dynamicId}/counters`,
  oneOffJobs = `/:${dynamicId}/oneOffJobs`,
  updateById = `/:${dynamicId}`,
  dynamicNumber = 'number',
  dynamicPage = 'page',
  dynamicLimit = 'limit',
  dynamicAccount = 'account',
  dynamicApartment = 'apartment',
  dynamicHouse = 'house',
  dynamicName = 'name',
  dynamicStreet = 'street',
  dynamicSurname = 'surname',
  dynamicType = 'type',
  dynamicComment = 'comment',
  dynamicDocument = 'document',
}

export default Endpoints;
