const enum Endpoints {
  root = '/',
  //   register = '/register',
  login = '/signin',
  //   logout = '/logout',
  current = '/current',
  user = '/user',
  //   restorePass = '/restore-password',
  //   dynamicRestorePassToken = 'restorePasswordToken',
  //   updatePass = `${restorePass}/:${dynamicRestorePassToken}`,
  //   dynamicSearch = 'search',
  //   dynamicStatus = 'status',
  dynamicId = 'id',
  fullAccess = `/:${dynamicId}/fullAccess`,
  houses = `/:${dynamicId}/houses`,
  subscribers = `/:${dynamicId}/subscribers`,
  accounting = `/:${dynamicId}/accounting`,
  documents = `/:${dynamicId}/documents`,
  counters = `/:${dynamicId}/counters`,
  oneOffJobs = `/:${dynamicId}/oneOffJobs`,
  settings = `/:${dynamicId}/settings`,
  //   dynamicToken = 'token',
  //   dynamicPage = 'page',
  //   dynamicLimit = 'limit',
}

export default Endpoints;
